#!/usr/bin/env python3
"""Patch the TTS issue paragraph modal JS functions in show.blade.php"""

filepath = 'resources/views/audiobooks/show.blade.php'
content = open(filepath, 'rb').read()

old_block_start = b"         function openTtsIssueParagraphModal(encodedParagraph, encodedMatchedText = '') {"
end_marker = b"         function scrollToChapterFromIssueScan"

start_idx = content.find(old_block_start)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print(f"ERROR: start={start_idx}, end={end_idx}")
    exit(1)

new_block = (
    "         // State for TTS issue paragraph editing\n"
    "         let _ttsIssueChapterId = null;\n"
    "         let _ttsIssueOriginalParagraph = '';\n"
    "\n"
    "         function openTtsIssueParagraphModal(encodedParagraph, encodedMatchedText = '', chapterId = null) {\n"
    "             const modal = document.getElementById('ttsIssueParagraphModal');\n"
    "             const contentEl = document.getElementById('ttsIssueParagraphContent');\n"
    "             const metaEl = document.getElementById('ttsIssueParagraphMeta');\n"
    "             const saveMsg = document.getElementById('ttsIssueParagraphSaveMsg');\n"
    "\n"
    "             if (!modal || !contentEl || !metaEl) {\n"
    "                 return;\n"
    "             }\n"
    "\n"
    "             const esc = (typeof escapeHtml === 'function')\n"
    "                 ? escapeHtml\n"
    "                 : (text) => (text || '').replace(/&/g, '&amp;')\n"
    "                     .replace(/</g, '&lt;')\n"
    "                     .replace(/>/g, '&gt;')\n"
    "                     .replace(/\"/g, '&quot;')\n"
    "                     .replace(/'/g, '&#039;');\n"
    "\n"
    "             let paragraph = '';\n"
    "             let matchedText = '';\n"
    "\n"
    "             try {\n"
    "                 paragraph = decodeURIComponent(encodedParagraph || '');\n"
    "             } catch (e) {\n"
    "                 paragraph = encodedParagraph || '';\n"
    "             }\n"
    "\n"
    "             try {\n"
    "                 matchedText = decodeURIComponent(encodedMatchedText || '');\n"
    "             } catch (e) {\n"
    "                 matchedText = encodedMatchedText || '';\n"
    "             }\n"
    "\n"
    "             // Store state for save\n"
    "             _ttsIssueChapterId = chapterId;\n"
    "             _ttsIssueOriginalParagraph = paragraph;\n"
    "\n"
    "             metaEl.innerHTML = matchedText\n"
    "                 ? `T\u1eeb nghi l\u1ed7i: <code class=\"rounded bg-rose-100 px-1 py-0.5 text-[11px] text-rose-700\">${esc(matchedText)}</code>`\n"
    "                 : '';\n"
    "\n"
    "             // Reset save message\n"
    "             if (saveMsg) {\n"
    "                 saveMsg.classList.add('hidden');\n"
    "                 saveMsg.textContent = '';\n"
    "             }\n"
    "\n"
    "             // Set textarea content\n"
    "             contentEl.value = paragraph || '';\n"
    "\n"
    "             modal.classList.remove('hidden');\n"
    "             modal.classList.add('flex');\n"
    "\n"
    "             // Scroll to and highlight matched text in textarea\n"
    "             if (matchedText) {\n"
    "                 setTimeout(() => {\n"
    "                     const idx = paragraph.indexOf(matchedText);\n"
    "                     if (idx !== -1) {\n"
    "                         contentEl.focus();\n"
    "                         contentEl.setSelectionRange(idx, idx + matchedText.length);\n"
    "                         // Scroll textarea to show the selection\n"
    "                         const lineHeight = parseInt(getComputedStyle(contentEl).lineHeight) || 20;\n"
    "                         const charsPerLine = Math.max(1, Math.floor(contentEl.clientWidth / 8));\n"
    "                         const approxLine = Math.floor(idx / charsPerLine);\n"
    "                         contentEl.scrollTop = Math.max(0, approxLine * lineHeight - contentEl.clientHeight / 2);\n"
    "                     } else {\n"
    "                         contentEl.focus();\n"
    "                         contentEl.setSelectionRange(0, 0);\n"
    "                         contentEl.scrollTop = 0;\n"
    "                     }\n"
    "                 }, 80);\n"
    "             } else {\n"
    "                 setTimeout(() => {\n"
    "                     contentEl.focus();\n"
    "                     contentEl.setSelectionRange(0, 0);\n"
    "                     contentEl.scrollTop = 0;\n"
    "                 }, 80);\n"
    "             }\n"
    "         }\n"
    "\n"
    "         function closeTtsIssueParagraphModal() {\n"
    "             const modal = document.getElementById('ttsIssueParagraphModal');\n"
    "             if (!modal) {\n"
    "                 return;\n"
    "             }\n"
    "             modal.classList.add('hidden');\n"
    "             modal.classList.remove('flex');\n"
    "             _ttsIssueChapterId = null;\n"
    "             _ttsIssueOriginalParagraph = '';\n"
    "         }\n"
    "\n"
    "         async function saveTtsIssueParagraphEdit() {\n"
    "             const contentEl = document.getElementById('ttsIssueParagraphContent');\n"
    "             const saveBtn = document.getElementById('ttsIssueParagraphSaveBtn');\n"
    "             const saveMsg = document.getElementById('ttsIssueParagraphSaveMsg');\n"
    "\n"
    "             if (!contentEl || !_ttsIssueChapterId) {\n"
    "                 if (saveMsg) {\n"
    "                     saveMsg.textContent = 'L\u1ed7i: Kh\u00f4ng x\u00e1c \u0111\u1ecbnh \u0111\u01b0\u1ee3c chapter c\u1ea7n l\u01b0u.';\n"
    "                     saveMsg.className = 'mx-4 mb-1 text-xs text-red-600';\n"
    "                     saveMsg.classList.remove('hidden');\n"
    "                 }\n"
    "                 return;\n"
    "             }\n"
    "\n"
    "             const replacement = contentEl.value;\n"
    "             if (replacement === _ttsIssueOriginalParagraph) {\n"
    "                 if (saveMsg) {\n"
    "                     saveMsg.textContent = 'N\u1ed9i dung ch\u01b0a thay \u0111\u1ed5i.';\n"
    "                     saveMsg.className = 'mx-4 mb-1 text-xs text-gray-500';\n"
    "                     saveMsg.classList.remove('hidden');\n"
    "                 }\n"
    "                 return;\n"
    "             }\n"
    "\n"
    "             if (saveBtn) saveBtn.disabled = true;\n"
    "             if (saveMsg) {\n"
    "                 saveMsg.textContent = '\u0110ang l\u01b0u...';\n"
    "                 saveMsg.className = 'mx-4 mb-1 text-xs text-gray-500';\n"
    "                 saveMsg.classList.remove('hidden');\n"
    "             }\n"
    "\n"
    "             try {\n"
    "                 const audioBookId = {{ $audioBook->id }};\n"
    "                 const url = `/audiobooks/${audioBookId}/chapters/${_ttsIssueChapterId}/fix-paragraph`;\n"
    "                 const resp = await fetch(url, {\n"
    "                     method: 'PATCH',\n"
    "                     headers: {\n"
    "                         'Content-Type': 'application/json',\n"
    "                         'X-CSRF-TOKEN': document.querySelector('meta[name=\"csrf-token\"]')?.content || '',\n"
    "                         'Accept': 'application/json',\n"
    "                     },\n"
    "                     body: JSON.stringify({\n"
    "                         original: _ttsIssueOriginalParagraph,\n"
    "                         replacement: replacement,\n"
    "                     }),\n"
    "                 });\n"
    "\n"
    "                 const data = await resp.json();\n"
    "\n"
    "                 if (resp.ok && data.success) {\n"
    "                     _ttsIssueOriginalParagraph = replacement;\n"
    "                     if (saveMsg) {\n"
    "                         saveMsg.textContent = '\u2713 \u0110\u00e3 l\u01b0u th\u00e0nh c\u00f4ng.';\n"
    "                         saveMsg.className = 'mx-4 mb-1 text-xs text-emerald-600';\n"
    "                     }\n"
    "                 } else {\n"
    "                     if (saveMsg) {\n"
    "                         saveMsg.textContent = `L\u1ed7i: ${data.message || data.error || 'Kh\u00f4ng th\u1ec3 l\u01b0u.'}`;\n"
    "                         saveMsg.className = 'mx-4 mb-1 text-xs text-red-600';\n"
    "                     }\n"
    "                 }\n"
    "             } catch (err) {\n"
    "                 if (saveMsg) {\n"
    "                     saveMsg.textContent = `L\u1ed7i k\u1ebft n\u1ed1i: ${err.message}`;\n"
    "                     saveMsg.className = 'mx-4 mb-1 text-xs text-red-600';\n"
    "                 }\n"
    "             } finally {\n"
    "                 if (saveBtn) saveBtn.disabled = false;\n"
    "             }\n"
    "         }\n"
    "\n"
).encode('utf-8')

new_content = content[:start_idx] + new_block + content[end_idx:]
open(filepath, 'wb').write(new_content)
print(f"Done. File size: {len(new_content)} bytes")
